version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
  backend:
    container_name: honorsParking
    build: .
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:mysql://db:3306/example # 역할 확인
      db-username: example
      db-password: example