name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 커밋한 파일들을 불러옴
      - name: Github Repository 파일 불러오기
        # 레포지토리에 저장되어있는 코드 불러오는 라이브러리
        uses: actions/checkout@v4

      # Github Actions에 빌드, 테스트 할 때 필요한 JDK 설치
      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # application.yml 파일 생성
      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/config/application.yml

      # application.properties 파일 생성
      - name: application.properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/config/application.properties

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      # ECR에 접근할 수 있는 권한을 허용받기 위해
      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        # 라이브러리가 있음
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t honorsparking-be .
        # . 은 현재 경로의 Dockerfile을 기반으로 이미지 파일 생성

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag honorsparking-be ${{ steps.login-ecr.outputs.registry }}/honorsparking-be:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/honorsparking-be:latest

      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop honorsparking-be || true
            docker rm honorsparking-be || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/honorsparking-be:latest
            docker run -d --name honorsparking-be -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/honorsparking-be:latest
